### ISSUE TITLE
manideep moturi

### ISSUE THREAD

**Issue by manideepmoturi** [haakondr/graph-edit-distance-python#1]
Hi,
I used your code in python that is the Graph edit distance concept. In that code to test the distance between two graphs you used two json graph files that you got by converting a normal text sentence to json graph by parsing. Can you help me that how did you converted the normal text sentence to json graph with the required output like lemma,word,pos,deprel,rel. It will be really helpful for me in my project.

**Comment by haakondr** [comment]
I used a combination of Stanford pos-tagger and MaltParser (both java libraries). I primarily used MaltParser because my supervisor recommended it, but I had alot of trouble with its memory consumption, so there might be better implementations out there.

http://nlp.stanford.edu/software/tagger.shtml
http://www.maltparser.org/

**Comment by manideepmoturi** [comment]
Thank you Sir,


ca n you provide me any information that i acn perform this task in Python.

Respectfully
Manideep Moturi

**Comment by haakondr** [comment]
this SO post seems to cover how to use MaltParser from a Python runtime:

http://stackoverflow.com/questions/13207394/step-by-step-to-getting-malt-parser-in-nltk-to-work

I haven't tried this, but I would probably just go with running MaltParser with Java, and either setup a web API for live parsing or running MaltParser in a preprocessing step. I also published some utils code for doing dependency parsing, but I can't really say if it works, it's been a long time. Still, it may serve as an example:

https://github.com/haakondr/Dependency-Parser

**Comment by manideepmoturi** [comment]
thank you sir for providing the information and I will work on the
information given by you and can i message you when i need a small help
regarding my research in graph edit distance concept.

**Comment by haakondr** [comment]
Sure, it sounds interesting.
