### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by ghost** [haakondr/graph-edit-distance-python#2]
Hey,
do you mind adding a license under which the code can be used?
Kind regards and many thanks

**Comment by haakondr** [comment]
Added MIt licence. This project has not been maintained at all, but I could look into improving documentation + code quality.

If you are interested in graph edit distance algorithms, please let me know if you have any feedback.

This algorirhm was designed while I was studying and is designed specifically for graph edit distance between sentences (in a dependency graph). Would be nice to know if I should put some effort into generalizing the algorithm to more generic use cases
