### ISSUE TITLE
Example code?

### ISSUE THREAD

**Issue by r03ert0** [haakondr/graph-edit-distance-python#3]
Hello,

Is there any example on using your code? I would like to compare unweighted undirected graphs, eventually weighted undirected graphs. Would there be a way of coding an arbitrary graph into the format you use?

Thank you!

**Comment by haakondr** [comment]
I am working on a rewamp of the codebase with examples, though I can't make any promises to when this is done. The plan is to support networx graphs. If this is not a preferred format, do you have any other preferences?
